# Generated by Django 5.2.12 on 2026-03-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterventionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("fail_count_at_intervention", models.IntegerField()),
                ("idle_time_at_intervention", models.IntegerField()),
                ("chat_text_at_intervention", models.TextField(blank=True)),
                (
                    "trigger_reason",
                    models.CharField(
                        choices=[
                            ("silent_fatigue", "Silent Fatigue Detection"),
                            ("timeout", "API Timeout"),
                            ("api_error", "API Error"),
                            ("llm_success", "LLM Success"),
                        ],
                        max_length=50,
                    ),
                ),
                ("used_fallback", models.BooleanField()),
                ("npc_dialogue", models.TextField()),
                ("npc_emotion", models.CharField(max_length=50)),
                ("trigger_event", models.CharField(max_length=50)),
                ("fail_count_after", models.IntegerField(blank=True, null=True)),
                ("idle_time_after", models.IntegerField(blank=True, null=True)),
                ("recovery_detected", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "-timestamp"],
                        name="npc_interve_session_bd32c7_idx",
                    ),
                    models.Index(
                        fields=["trigger_reason"], name="npc_interve_trigger_c96903_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InterventionOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fail_count_post", models.IntegerField()),
                ("idle_time_post", models.IntegerField()),
                ("chat_resumed", models.BooleanField(default=False)),
                ("recovery", models.BooleanField()),
                ("improvement_score", models.FloatField(blank=True, null=True)),
                ("measured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="npc.interventionlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-measured_at"],
            },
        ),
    ]
