# Generated by Django 5.2.12 on 2026-03-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interventionlog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "NPC 개입 기록 (Intervention Log)",
                "verbose_name_plural": "1. NPC 개입 기록 모아보기",
            },
        ),
        migrations.AlterModelOptions(
            name="interventionoutcome",
            options={
                "ordering": ["-measured_at"],
                "verbose_name": "개입 효과 측정 결과 (Outcome)",
                "verbose_name_plural": "2. 개입 효과 측정 결과 모아보기",
            },
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="chat_text_at_intervention",
            field=models.TextField(blank=True, verbose_name="당시 입력한 채팅"),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="fail_count_after",
            field=models.IntegerField(blank=True, null=True, verbose_name="개입 후 실패 횟수"),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="fail_count_at_intervention",
            field=models.IntegerField(verbose_name="당시 실패 횟수"),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="idle_time_after",
            field=models.IntegerField(blank=True, null=True, verbose_name="개입 후 대기 시간"),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="idle_time_at_intervention",
            field=models.IntegerField(verbose_name="당시 대기 시간(초)"),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="npc_dialogue",
            field=models.TextField(verbose_name="NPC 출력 대사"),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="npc_emotion",
            field=models.CharField(max_length=50, verbose_name="NPC 감정 상태"),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="recovery_detected",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="상태 호전(Recovery) 여부"
            ),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="session_id",
            field=models.CharField(db_index=True, max_length=100, verbose_name="세션 ID"),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="개입 발생 시간"),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="trigger_event",
            field=models.CharField(max_length=50, verbose_name="발동된 게임 이벤트"),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="trigger_reason",
            field=models.CharField(
                choices=[
                    ("silent_fatigue", "조용한 피로 (Silent Fatigue)"),
                    ("timeout", "API 응답 지연 (Timeout)"),
                    ("api_error", "API 통신 오류 (Error)"),
                    ("llm_success", "AI 정상 응답 (LLM Success)"),
                ],
                max_length=50,
                verbose_name="개입 발생 원인",
            ),
        ),
        migrations.AlterField(
            model_name="interventionlog",
            name="used_fallback",
            field=models.BooleanField(verbose_name="대체 응답(Fallback) 사용 여부"),
        ),
        migrations.AlterField(
            model_name="interventionoutcome",
            name="chat_resumed",
            field=models.BooleanField(default=False, verbose_name="채팅 재개 여부"),
        ),
        migrations.AlterField(
            model_name="interventionoutcome",
            name="fail_count_post",
            field=models.IntegerField(verbose_name="5회 행동 후 실패 횟수"),
        ),
        migrations.AlterField(
            model_name="interventionoutcome",
            name="idle_time_post",
            field=models.IntegerField(verbose_name="5회 행동 후 대기 시간"),
        ),
        migrations.AlterField(
            model_name="interventionoutcome",
            name="improvement_score",
            field=models.FloatField(blank=True, null=True, verbose_name="개선율(Score)"),
        ),
        migrations.AlterField(
            model_name="interventionoutcome",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outcomes",
                to="npc.interventionlog",
                verbose_name="연결된 개입 기록",
            ),
        ),
        migrations.AlterField(
            model_name="interventionoutcome",
            name="measured_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="효과 측정 시간"),
        ),
        migrations.AlterField(
            model_name="interventionoutcome",
            name="recovery",
            field=models.BooleanField(verbose_name="상태 호전(Recovery) 판정"),
        ),
    ]
